### ISSUE TITLE
error 404 not found when hitting trakteer API

### ISSUE THREAD

**Issue by RSurya99** [BbayuGt/Trakteer.js#36]
I have added my pageID to be the same as my trakteer account, but the package throw an error API not found when trying to request to trakteer API, is the API wrong or something else?
![trakteerjs-error](https://user-images.githubusercontent.com/73375663/187068883-503d2b2b-47a4-4b46-8b53-697f300b85b7.png)

**Comment by BbayuGt** [comment]
Can you send me what's inside your `new Client()`?

**Comment by RSurya99** [comment]
![image](https://user-images.githubusercontent.com/73375663/189020492-660665a6-fea8-4aca-8f2a-600d6fa8a2f6.png)

**Comment by BbayuGt** [comment]
change the "PageID" (first parameter) to your page id, you can view it here
![image](https://user-images.githubusercontent.com/49893593/189038867-ed0ee3ed-9d7c-442e-81d9-81a676ecdd3d.png)

the second parameter will be the trstream-xxx, you can check it at https://trakteer.id/manage/stream-settings/settings

**Comment by RSurya99** [comment]
it work, thanks
